version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sky31
    environment:
      DATABASE_URI: mysql+pymysql://root:sky31admin@db/sky31_leaveRequest

  db:
    image: mariadb:latest
    networks:
      - sky31
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化 SQL（仅第一次有效）
      - db_data:/var/lib/mysql   # 持久化 MariaDB 数据
    environment:
      MYSQL_ROOT_PASSWORD: sky31admin
      MYSQL_DATABASE: sky31Employees
      MYSQL_USER: admin
      MYSQL_PASSWORD: sky31admin

  redis:
    image: redis:latest
    networks:
      - sky31


volumes:
  db_data:
networks:
  - sky31:
